//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Screenshot_Manager_Module.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Screenshot_Manager_Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A duplicate image name was specified! ähnelt.
        /// </summary>
        internal static string A_duplicate_image_name_was_specified_ {
            get {
                return ResourceManager.GetString("A duplicate image name was specified!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click To Zoom ähnelt.
        /// </summary>
        internal static string Click_To_Zoom {
            get {
                return ResourceManager.GetString("Click To Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Image? ähnelt.
        /// </summary>
        internal static string Delete_Image_ {
            get {
                return ResourceManager.GetString("Delete Image?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to delete image. {0} ähnelt.
        /// </summary>
        internal static string Failed_to_delete_image___0_ {
            get {
                return ResourceManager.GetString("Failed to delete image. {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Favourite ähnelt.
        /// </summary>
        internal static string Favourite {
            get {
                return ResourceManager.GetString("Favourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image name cannot be empty. ähnelt.
        /// </summary>
        internal static string Image_name_cannot_be_empty_ {
            get {
                return ResourceManager.GetString("Image name cannot be empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a different image name. ähnelt.
        /// </summary>
        internal static string Please_enter_a_different_image_name_ {
            get {
                return ResourceManager.GetString("Please enter a different image name.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename Image ähnelt.
        /// </summary>
        internal static string Rename_Image {
            get {
                return ResourceManager.GetString("Rename Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screenshot Created! ähnelt.
        /// </summary>
        internal static string Screenshot_Created_ {
            get {
                return ResourceManager.GetString("Screenshot Created!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search... ähnelt.
        /// </summary>
        internal static string Search___ {
            get {
                return ResourceManager.GetString("Search...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following characters are not allowed: {0} ähnelt.
        /// </summary>
        internal static string The_following_characters_are_not_allowed___0_ {
            get {
                return ResourceManager.GetString("The following characters are not allowed: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The image doesn&apos;t exist anymore! ähnelt.
        /// </summary>
        internal static string The_image_file_doesn_t_exist_anymore_ {
            get {
                return ResourceManager.GetString("The image file doesn\'t exist anymore!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The image is in use by another process. ähnelt.
        /// </summary>
        internal static string The_image_file_is_in_use_by_another_process_ {
            get {
                return ResourceManager.GetString("The image file is in use by another process.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The image name contains invalid characters. ähnelt.
        /// </summary>
        internal static string The_image_name_contains_invalid_characters_ {
            get {
                return ResourceManager.GetString("The image name contains invalid characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to rename image. {0} ähnelt.
        /// </summary>
        internal static string Unable_to_rename_image___0_ {
            get {
                return ResourceManager.GetString("Unable to rename image. {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unfavourite ähnelt.
        /// </summary>
        internal static string Unfavourite {
            get {
                return ResourceManager.GetString("Unfavourite", resourceCulture);
            }
        }
    }
}
