//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Universal_Search_Module.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Universal_Search_Module.Strings.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Search.
        /// </summary>
        internal static string Icon_Title {
            get {
                return ResourceManager.GetString("Icon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closest Waypoint.
        /// </summary>
        internal static string Landmark_Details_ClosestWaypoint {
            get {
                return ResourceManager.GetString("Landmark_Details_ClosestWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none found.
        /// </summary>
        internal static string Landmark_Details_ClosestWaypoint_NoneFound {
            get {
                return ResourceManager.GetString("Landmark_Details_ClosestWaypoint_NoneFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click: Copy chat code to clipboard..
        /// </summary>
        internal static string Landmark_Details_CopyChatCode {
            get {
                return ResourceManager.GetString("Landmark_Details_CopyChatCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift + Click: Copy closest waypoint to clipboard..
        /// </summary>
        internal static string Landmark_Details_CopyClosestWaypoint {
            get {
                return ResourceManager.GetString("Landmark_Details_CopyClosestWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy nearest waypoint to clipboard. Try again..
        /// </summary>
        internal static string Landmark_FailedToCopy {
            get {
                return ResourceManager.GetString("Landmark_FailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied nearest waypoint to clipboard!.
        /// </summary>
        internal static string Landmark_WaypointCopied {
            get {
                return ResourceManager.GetString("Landmark_WaypointCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landmarks.
        /// </summary>
        internal static string SearchHandler_Landmarks {
            get {
                return ResourceManager.GetString("SearchHandler_Landmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string SearchHandler_Skills {
            get {
                return ResourceManager.GetString("SearchHandler_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        internal static string SearchHandler_Traits {
            get {
                return ResourceManager.GetString("SearchHandler_Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied chat link to clipboard!.
        /// </summary>
        internal static string SearchItem_Copied {
            get {
                return ResourceManager.GetString("SearchItem_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy chat link to clipboard. Try again..
        /// </summary>
        internal static string SearchItem_FailedToCopy {
            get {
                return ResourceManager.GetString("SearchItem_FailedToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the chat code will automatically entered into the ingame chat.
        /// </summary>
        internal static string Settings_EnterSelectionIntoChat_Text {
            get {
                return ResourceManager.GetString("Settings_EnterSelectionIntoChat_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Selection Into Chat Automatically.
        /// </summary>
        internal static string Settings_EnterSelectionIntoChat_Title {
            get {
                return ResourceManager.GetString("Settings_EnterSelectionIntoChat_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the landmark search window will automatically hide after a landmark is selected from the results..
        /// </summary>
        internal static string Settings_HideWindowAfterSelection_Text {
            get {
                return ResourceManager.GetString("Settings_HideWindowAfterSelection_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Window After Selection.
        /// </summary>
        internal static string Settings_HideWindowAfterSelection_Title {
            get {
                return ResourceManager.GetString("Settings_HideWindowAfterSelection_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, a notification will be displayed in the center of the screen confirming the landmark was copied..
        /// </summary>
        internal static string Settings_NotificationAfterCopy_Text {
            get {
                return ResourceManager.GetString("Settings_NotificationAfterCopy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification When Landmark is Copied.
        /// </summary>
        internal static string Settings_NotificationAfterCopy_Title {
            get {
                return ResourceManager.GetString("Settings_NotificationAfterCopy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks Stun.
        /// </summary>
        internal static string SkillTooltip_BreaksStun {
            get {
                return ResourceManager.GetString("SkillTooltip_BreaksStun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string SkillTooltip_Chance {
            get {
                return ResourceManager.GetString("SkillTooltip_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Only.
        /// </summary>
        internal static string SkillTooltip_CombatOnly {
            get {
                return ResourceManager.GetString("SkillTooltip_CombatOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain {0} Based on a Percentage of {1}: {2}%.
        /// </summary>
        internal static string TraitTooltip_BuffConversion {
            get {
                return ResourceManager.GetString("TraitTooltip_BuffConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chance.
        /// </summary>
        internal static string TraitTooltip_Chance {
            get {
                return ResourceManager.GetString("TraitTooltip_Chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Only.
        /// </summary>
        internal static string TraitTooltip_CombatOnly {
            get {
                return ResourceManager.GetString("TraitTooltip_CombatOnly", resourceCulture);
            }
        }
    }
}
