//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Events_Module.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Events_Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Concert for the Ages.
        /// </summary>
        internal static string A_Concert_for_the_Ages {
            get {
                return ResourceManager.GetString("A Concert for the Ages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admiral Taidha Covington.
        /// </summary>
        internal static string Admiral_Taidha_Covington {
            get {
                return ResourceManager.GetString("Admiral Taidha Covington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advancing on the Blighting Towers.
        /// </summary>
        internal static string Advancing_on_the_Blighting_Towers {
            get {
                return ResourceManager.GetString("Advancing on the Blighting Towers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        internal static string All_Events {
            get {
                return ResourceManager.GetString("All Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alphabetical.
        /// </summary>
        internal static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle in Tarir.
        /// </summary>
        internal static string Battle_in_Tarir {
            get {
                return ResourceManager.GetString("Battle in Tarir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino Blitz.
        /// </summary>
        internal static string Casino_Blitz {
            get {
                return ResourceManager.GetString("Casino Blitz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceremony of the Sacred Flame.
        /// </summary>
        internal static string Ceremony_of_the_Sacred_Flame {
            get {
                return ResourceManager.GetString("Ceremony of the Sacred Flame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chak Gerent.
        /// </summary>
        internal static string Chak_Gerent {
            get {
                return ResourceManager.GetString("Chak Gerent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choya Piñata.
        /// </summary>
        internal static string Choya_Pinata {
            get {
                return ResourceManager.GetString("Choya Pinata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claw of Jormag.
        /// </summary>
        internal static string Claw_of_Jormag {
            get {
                return ResourceManager.GetString("Claw of Jormag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to toggle tracking for this event..
        /// </summary>
        internal static string Click_to_toggle_tracking_for_this_event_ {
            get {
                return ResourceManager.GetString("Click to toggle tracking for this event.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied waypoint to clipboard!.
        /// </summary>
        internal static string Copied_waypoint_to_clipboard_ {
            get {
                return ResourceManager.GetString("Copied waypoint to clipboard!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Site.
        /// </summary>
        internal static string Crash_Site {
            get {
                return ResourceManager.GetString("Crash Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dangerous Prey.
        /// </summary>
        internal static string Dangerous_Prey {
            get {
                return ResourceManager.GetString("Dangerous Prey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dawn.
        /// </summary>
        internal static string Dawn {
            get {
                return ResourceManager.GetString("Dawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day-Night Cycle.
        /// </summary>
        internal static string Day_Night_Cycle {
            get {
                return ResourceManager.GetString("Day-Night Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defending Tarir.
        /// </summary>
        internal static string Defending_Tarir {
            get {
                return ResourceManager.GetString("Defending Tarir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drakkar, the Ice Dragon&apos;s Champion.
        /// </summary>
        internal static string Drakkar__the_Ice_Dragon_s_Champion {
            get {
                return ResourceManager.GetString("Drakkar, the Ice Dragon\'s Champion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dusk.
        /// </summary>
        internal static string Dusk {
            get {
                return ResourceManager.GetString("Dusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Notifications.
        /// </summary>
        internal static string Enable_Notifications {
            get {
                return ResourceManager.GetString("Enable Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Categories.
        /// </summary>
        internal static string Event_Categories {
            get {
                return ResourceManager.GetString("Event Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Search.
        /// </summary>
        internal static string Event_Search {
            get {
                return ResourceManager.GetString("Event Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events and Metas.
        /// </summary>
        internal static string Events_and_Metas {
            get {
                return ResourceManager.GetString("Events and Metas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolved Jungle Wurm.
        /// </summary>
        internal static string Evolved_Jungle_Wurm {
            get {
                return ResourceManager.GetString("Evolved Jungle Wurm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy waypoint to clipboard. Try again..
        /// </summary>
        internal static string Failed_to_copy_waypoint_to_clipboard__Try_again_ {
            get {
                return ResourceManager.GetString("Failed to copy waypoint to clipboard. Try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load metas from events.json!.
        /// </summary>
        internal static string Failed_to_load_metas_from_events_json_ {
            get {
                return ResourceManager.GetString("Failed to load metas from events.json!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fire Elemental.
        /// </summary>
        internal static string Fire_Elemental {
            get {
                return ResourceManager.GetString("Fire Elemental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged with Fire.
        /// </summary>
        internal static string Forged_with_Fire {
            get {
                return ResourceManager.GetString("Forged with Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great Jungle Wurm.
        /// </summary>
        internal static string Great_Jungle_Wurm {
            get {
                return ResourceManager.GetString("Great Jungle Wurm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Event.
        /// </summary>
        internal static string Group_Event {
            get {
                return ResourceManager.GetString("Group Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Events.
        /// </summary>
        internal static string Hidden_Events {
            get {
                return ResourceManager.GetString("Hidden Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquest Golem Mark II.
        /// </summary>
        internal static string Inquest_Golem_Mark_II {
            get {
                return ResourceManager.GetString("Inquest Golem Mark II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junundu Rising.
        /// </summary>
        internal static string Junundu_Rising {
            get {
                return ResourceManager.GetString("Junundu Rising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karka Queen.
        /// </summary>
        internal static string Karka_Queen {
            get {
                return ResourceManager.GetString("Karka Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley-Line Anomaly (Gendarran Fields).
        /// </summary>
        internal static string Ley_Line_Anomaly__Gendarran_Fields_ {
            get {
                return ResourceManager.GetString("Ley-Line Anomaly (Gendarran Fields)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley-Line Anomaly (Iron Marches).
        /// </summary>
        internal static string Ley_Line_Anomaly__Iron_Marches_ {
            get {
                return ResourceManager.GetString("Ley-Line Anomaly (Iron Marches)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ley-Line Anomaly (Timberline Falls).
        /// </summary>
        internal static string Ley_Line_Anomaly__Timberline_Falls_ {
            get {
                return ResourceManager.GetString("Ley-Line Anomaly (Timberline Falls)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maws of Torment.
        /// </summary>
        internal static string Maws_of_Torment {
            get {
                return ResourceManager.GetString("Maws of Torment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megadestroyer.
        /// </summary>
        internal static string Megadestroyer {
            get {
                return ResourceManager.GetString("Megadestroyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Event.
        /// </summary>
        internal static string Meta_Event {
            get {
                return ResourceManager.GetString("Meta Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modniir Ulgoth.
        /// </summary>
        internal static string Modniir_Ulgoth {
            get {
                return ResourceManager.GetString("Modniir Ulgoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Notifications.
        /// </summary>
        internal static string Mute_Notifications {
            get {
                return ResourceManager.GetString("Mute Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearby waypoint: {0}.
        /// </summary>
        internal static string Nearby_waypoint___0_ {
            get {
                return ResourceManager.GetString("Nearby waypoint: {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Up.
        /// </summary>
        internal static string Next_Up {
            get {
                return ResourceManager.GetString("Next Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night and the Enemy.
        /// </summary>
        internal static string Night_and_the_Enemy {
            get {
                return ResourceManager.GetString("Night and the Enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Bosses.
        /// </summary>
        internal static string Night_Bosses {
            get {
                return ResourceManager.GetString("Night Bosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left click to copy waypoint.
        ///Right click to dismiss..
        /// </summary>
        internal static string Notification_Tooltip {
            get {
                return ResourceManager.GetString("Notification_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palawadan, Jewel of Istan.
        /// </summary>
        internal static string Palawadan__Jewel_of_Istan {
            get {
                return ResourceManager.GetString("Palawadan, Jewel of Istan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read about this event on the wiki..
        /// </summary>
        internal static string Read_about_this_event_on_the_wiki_ {
            get {
                return ResourceManager.GetString("Read about this event on the wiki.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandstorm.
        /// </summary>
        internal static string Sandstorm {
            get {
                return ResourceManager.GetString("Sandstorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Securing Verdant Brink.
        /// </summary>
        internal static string Securing_Verdant_Brink {
            get {
                return ResourceManager.GetString("Securing Verdant Brink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serpents&apos; Ire.
        /// </summary>
        internal static string Serpents__Ire {
            get {
                return ResourceManager.GetString("Serpents\' Ire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Reset.
        /// </summary>
        internal static string Server_Reset {
            get {
                return ResourceManager.GetString("Server Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow Behemoth.
        /// </summary>
        internal static string Shadow_Behemoth {
            get {
                return ResourceManager.GetString("Shadow Behemoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts in {0}.
        /// </summary>
        internal static string Starts_in__0_ {
            get {
                return ResourceManager.GetString("Starts in {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storms of Winter.
        /// </summary>
        internal static string Storms_of_Winter {
            get {
                return ResourceManager.GetString("Storms of Winter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svanir Shaman Chief.
        /// </summary>
        internal static string Svanir_Shaman_Chief {
            get {
                return ResourceManager.GetString("Svanir Shaman Chief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tequatl the Sunless.
        /// </summary>
        internal static string Tequatl_the_Sunless {
            get {
                return ResourceManager.GetString("Tequatl the Sunless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Haunting of Doomlore Shrine.
        /// </summary>
        internal static string The_Haunting_of_Doomlore_Shrine {
            get {
                return ResourceManager.GetString("The Haunting of Doomlore Shrine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Oil Floes.
        /// </summary>
        internal static string The_Oil_Floes {
            get {
                return ResourceManager.GetString("The Oil Floes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Ooze Pit Trials.
        /// </summary>
        internal static string The_Ooze_Pit_Trials {
            get {
                return ResourceManager.GetString("The Ooze Pit Trials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Path to Ascension.
        /// </summary>
        internal static string The_Path_to_Ascension {
            get {
                return ResourceManager.GetString("The Path to Ascension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Search for Buried Treasure.
        /// </summary>
        internal static string The_Search_for_Buried_Treasure {
            get {
                return ResourceManager.GetString("The Search for Buried Treasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Shatterer.
        /// </summary>
        internal static string The_Shatterer {
            get {
                return ResourceManager.GetString("The Shatterer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thunderhead Keep.
        /// </summary>
        internal static string Thunderhead_Keep {
            get {
                return ResourceManager.GetString("Thunderhead Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial by Fire.
        /// </summary>
        internal static string Trial_by_Fire {
            get {
                return ResourceManager.GetString("Trial by Fire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Event Times:.
        /// </summary>
        internal static string Upcoming_Event_Times_ {
            get {
                return ResourceManager.GetString("Upcoming Event Times:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Bosses.
        /// </summary>
        internal static string World_Bosses {
            get {
                return ResourceManager.GetString("World Bosses", resourceCulture);
            }
        }
    }
}
